# Generated by Django 5.1.2 on 2024-10-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Weightlifting', 'Weightlifting')], max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
