# Generated by Django 5.1.2 on 2024-10-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='Calories burned', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distance in Kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
